name: build
on:
  push:
    tags:
      - 'v*.*.*'

  workflow_run:
    workflows: ["Go Tests"]
    types:
      - completed
jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: tag
        id: tag
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          tag='{{ ref }}-{{ dateTime }}-{{ commit }}'
          if [[ "$IS_TAG" == "true" ]]; then
            tag='{{ ref }}'
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - uses: tapclap/build-images-action@main
        id: build-images
        with:
          registry: ghcr.io
          registry-user: ${{ github.repository_owner }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          latest: true
          tag: ${{ steps.tag.outputs.tag }}
          operation: build-and-push
          build-opts: |
            - name: checker
              repo-image-name: true